name: snapshot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install nebula-graph
        run: |
          mkdir tmp
          pushd tmp
          git clone https://github.com/vesoft-inc/nebula-docker-compose.git
          pushd nebula-docker-compose/
          cp ../../src/test/resources/docker-compose.yaml .
          docker-compose up -d
          sleep 30
          docker-compose ps
          popd
          popd

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish package
        run: mvn --batch-mode deploy -Dmaven.javadoc.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
